on:
  issues:
    types: [opened]

jobs:
  issue_labeler:
    if: github.repository == 'atidot3/Pandaria'
    runs-on: ubuntu-latest
    name: Issue Labeler
    steps:
    - name: Issue Labeler
      id: issue-labeler
      uses: atidot3/GitHub-Actions@issue-labeler-prod
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

